# User config
author: "Devi Acharya"
tagline: "Devi's Portfolio"
description: "I'm Devi Acharya -- a game developer and researcher currently pursuing my Ph.D. in Computational Media at the University of California - Santa Cruz."
keywords: ""
email: "dacharya64@gmail.com"
linkedin: "https://www.linkedin.com/in/dacharya"
twitter: "https://twitter.com/dacharya64"
github: "https://github.com/dacharya64"

# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
